services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5000:5432"
  django:
    image: task-manager-django:latest
    container_name: reading-room-django
    restart: unless-stopped
    command: sh gunicorn.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
