services:
  django:
    image: task-manager-django:latest
    container_name: reading-room-django
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  proxynet: