services:
  nginx:
    image: task-manager-nginx:latest
    container_name: task-manager-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - django-static:/var/www/static
      - django-media:/var/www/media
    depends_on:
      - django
    networks:
      - proxynet
  db:
    image: postgres
    container_name: task-manager-postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - proxynet
  django:
    image: task-manager-django:latest
    container_name: task-manager-django
    restart: unless-stopped
    command: sh gunicorn.sh
    volumes:
      - django-static:/code/static
      - django-media:/code/media
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - proxynet

networks:
  proxynet:

volumes:
  django-static:
  django-media: