# Generated by Django 3.2.8 on 2021-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('finish_date', models.DateField(verbose_name='Дата завершения')),
                ('attached_file', models.FileField(upload_to='', verbose_name='Прикрипленный файл')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
