# Generated by Django 3.2.8 on 2021-10-09 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
