# Generated by Django 3.2.8 on 2021-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
