# Generated by Django 3.2.8 on 2021-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Прикрипленный файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=None, verbose_name='Дата завершения'),
            preserve_default=False,
        ),
    ]
